import logging

STRINGS = {
    "BETUFEMGDL": "A-1-11th ACR",
    "SLWSVLLPZP": "Troop HQ",
    "DLZTKEQFFT": "1st Tank Platoon",
    "UQOKRWWLYC": "2nd Tank Platoon",
    "EBAXRQFWNO": "Recon Platoon",
    "FQMCKESHIX": "Air Defense Platoon",
    "HYKDXVFKPJ": "4311-VKK 431",
    "QPXHKBIWGL": "Führung",
    "OIQGCEKCDM": "1. Zug",
    "CRZWJJYXZT": "2. Zug",
    "OPDTEQBKBP": "Artillerie-Gruppe",
    "EHFLKHNINV": "Flak-Gruppe",
    "cha_1": "Air Support",
    "FCSWUWUIEP": "1-A-509th TFS",
    "ZOMQAFHITM": "Rota Komandovani",
    "SUJBJHQBBH": "Platoon HQ",
    "HBLUTIMQXB": "AA Platoon",
    "KPNJIRFMVK": "Artillery Platoon",
    "YHHKVXFYTB": "1-1-17y GvTP",
    "AEHXPSCGSH": "1st Platoon",
    "TXLIVWUPSM": "2nd Platoon",
    "WAKIQBNMIP": "3rd Platoon",
    "JFDLGUGPAH": "4th Platoon",
    "BIUSBBTLXM": "2-1-17y GvTP",
    "CDWDIWURMP": "1-1-35ya GvDShB",
    "cha_2": "Aviapodderzhka",
    "ZRMILCMBPM": "HQ-2-32nd Armored",
    "AFXAGTUHDY": "Support Group",
    "ZISMTAUYGO": "AA Group",
    "JYZDSITBSM": "Mortar Platoon",
    "SRHWTUYLYQ": "Logistics Group",
    "YRYIJYWVRT": "E-2-32nd Armored",
    "LGWJRRZQVH": "N-4-7th Cavalry",
    "MWICGOJROV": "1-900y DShBat.",
    "GHUYXATXPF": "2-900y DShBat.",
    "AIIMCNDONF": "Recon Platoon",
    "MMISGNOMQO": "AT Platoon",
    "OMMSABUJXJ": "Support Platoon",
    "LSKTJWMLCY": "SK-1-MSR17",
    "AAIWEZVTZN": "MG-Gruppe",
    "FGPDEUABPI": "Aufkl.-Gruppe",
    "FPKZLIBICB": "Fla.-Gruppe",
    "IHCDFIICYD": "1-1-MSR17",
    "XSQBUZHFTL": "3. Zug",
    "VWPETUIMJA": "2-1-MSR17",
    "VGGMGCGPJS": "1-PJA11",
    "cha_4": "Luftunterstützung",
    "IJOVDIJCWA": "Company HQ",
    "cha_5": "Inf. Company",
    "cha_7": "Recon. Company",
    "cha_6": "Arm. Company",
    "cha_3": "3rd Squadron",
    "MOQJAJQKCU": "HQ-Blues and Royals",
    "WBESWFYVOK": "Recon Troop",
    "TABDGYHUPF": "ATGW Troop",
    "RCWSMVEAWA": "A-Blues and Royals",
    "GITRTZAZLS": "1st Troop",
    "MATKYCBLCT": "2nd Troop",
    "NQZWSPPSTW": "3rd Troop",
}


def get_string(token: str):
    if not STRINGS.__contains__(token):
        logging.warning("String for token \"" + token + "\" not found!")
        return "String not found!"
    return STRINGS[token]
